//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace TestExperiment
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class ArducamOV9180
    {
    
        private string _cameraType;
    
        private double _triggerFrequency;
    
        private int _deviceIndex;
    
        public ArducamOV9180()
        {
            _cameraType = "Arducam";
            _triggerFrequency = 50D;
            _deviceIndex = 0;
        }
    
        protected ArducamOV9180(ArducamOV9180 other)
        {
            _cameraType = other._cameraType;
            _triggerFrequency = other._triggerFrequency;
            _deviceIndex = other._deviceIndex;
        }
    
        /// <summary>
        /// Camera type discriminator for Arducam devices.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="cameraType")]
        [System.ComponentModel.DescriptionAttribute("Camera type discriminator for Arducam devices.")]
        public string CameraType
        {
            get
            {
                return _cameraType;
            }
            set
            {
                _cameraType = value;
            }
        }
    
        /// <summary>
        /// The frequency at which the camera is triggered (in Hz).
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="triggerFrequency")]
        [System.ComponentModel.DescriptionAttribute("The frequency at which the camera is triggered (in Hz).")]
        public double TriggerFrequency
        {
            get
            {
                return _triggerFrequency;
            }
            set
            {
                _triggerFrequency = value;
            }
        }
    
        /// <summary>
        /// The index of the device.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="deviceIndex")]
        [System.ComponentModel.DescriptionAttribute("The index of the device.")]
        public int DeviceIndex
        {
            get
            {
                return _deviceIndex;
            }
            set
            {
                _deviceIndex = value;
            }
        }
    
        public System.IObservable<ArducamOV9180> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new ArducamOV9180(this)));
        }
    
        public System.IObservable<ArducamOV9180> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new ArducamOV9180(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("CameraType = " + _cameraType + ", ");
            stringBuilder.Append("TriggerFrequency = " + _triggerFrequency + ", ");
            stringBuilder.Append("DeviceIndex = " + _deviceIndex);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Represents an Arduino serial device used in Bonsai workflows.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Represents an Arduino serial device used in Bonsai workflows.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class ArduinoDevice
    {
    
        private string _deviceType;
    
        private string _portName;
    
        private int _baudRate;
    
        private int _samplingInterval;
    
        private LedDriver _ledDriver;
    
        public ArduinoDevice()
        {
            _deviceType = "Arduino";
            _baudRate = 9600;
        }
    
        protected ArduinoDevice(ArduinoDevice other)
        {
            _deviceType = other._deviceType;
            _portName = other._portName;
            _baudRate = other._baudRate;
            _samplingInterval = other._samplingInterval;
            _ledDriver = other._ledDriver;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="deviceType")]
        public string DeviceType
        {
            get
            {
                return _deviceType;
            }
            set
            {
                _deviceType = value;
            }
        }
    
        /// <summary>
        /// The name of the device serial port.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="portName")]
        [System.ComponentModel.DescriptionAttribute("The name of the device serial port.")]
        public string PortName
        {
            get
            {
                return _portName;
            }
            set
            {
                _portName = value;
            }
        }
    
        /// <summary>
        /// Baud rate for serial communication.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="baudRate")]
        [System.ComponentModel.DescriptionAttribute("Baud rate for serial communication.")]
        public int BaudRate
        {
            get
            {
                return _baudRate;
            }
            set
            {
                _baudRate = value;
            }
        }
    
        /// <summary>
        /// Sampling interval, in milliseconds, between analog and I2C measurements.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="samplingInterval")]
        [System.ComponentModel.DescriptionAttribute("Sampling interval, in milliseconds, between analog and I2C measurements.")]
        public int SamplingInterval
        {
            get
            {
                return _samplingInterval;
            }
            set
            {
                _samplingInterval = value;
            }
        }
    
        /// <summary>
        /// Optional LedDriver module for generating digital output pulses.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ledDriver")]
        [System.ComponentModel.DescriptionAttribute("Optional LedDriver module for generating digital output pulses.")]
        public LedDriver LedDriver
        {
            get
            {
                return _ledDriver;
            }
            set
            {
                _ledDriver = value;
            }
        }
    
        public System.IObservable<ArduinoDevice> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new ArduinoDevice(this)));
        }
    
        public System.IObservable<ArduinoDevice> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new ArduinoDevice(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("DeviceType = " + _deviceType + ", ");
            stringBuilder.Append("PortName = " + _portName + ", ");
            stringBuilder.Append("BaudRate = " + _baudRate + ", ");
            stringBuilder.Append("SamplingInterval = " + _samplingInterval + ", ");
            stringBuilder.Append("LedDriver = " + _ledDriver);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Represents a Harp Behavior Board device.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Represents a Harp Behavior Board device.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class BehaviorBoard
    {
    
        private string _deviceType;
    
        private string _portName;
    
        private PulseController _pulseController;
    
        private CameraController _cameraController;
    
        private RunningWheelModule _runningWheel;
    
        public BehaviorBoard()
        {
            _deviceType = "BehaviorBoard";
        }
    
        protected BehaviorBoard(BehaviorBoard other)
        {
            _deviceType = other._deviceType;
            _portName = other._portName;
            _pulseController = other._pulseController;
            _cameraController = other._cameraController;
            _runningWheel = other._runningWheel;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="deviceType")]
        public string DeviceType
        {
            get
            {
                return _deviceType;
            }
            set
            {
                _deviceType = value;
            }
        }
    
        /// <summary>
        /// The name of the device serial port.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="portName")]
        [System.ComponentModel.DescriptionAttribute("The name of the device serial port.")]
        public string PortName
        {
            get
            {
                return _portName;
            }
            set
            {
                _portName = value;
            }
        }
    
        /// <summary>
        /// Optional PulseController module for generating digital output pulses.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="pulseController")]
        [System.ComponentModel.DescriptionAttribute("Optional PulseController module for generating digital output pulses.")]
        public PulseController PulseController
        {
            get
            {
                return _pulseController;
            }
            set
            {
                _pulseController = value;
            }
        }
    
        /// <summary>
        /// Optional CameraController module for emitting camera trigger pulses.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="cameraController")]
        [System.ComponentModel.DescriptionAttribute("Optional CameraController module for emitting camera trigger pulses.")]
        public CameraController CameraController
        {
            get
            {
                return _cameraController;
            }
            set
            {
                _cameraController = value;
            }
        }
    
        /// <summary>
        /// Optional RunningWheelModule module to define wheel geometry.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="runningWheel")]
        [System.ComponentModel.DescriptionAttribute("Optional RunningWheelModule module to define wheel geometry.")]
        public RunningWheelModule RunningWheel
        {
            get
            {
                return _runningWheel;
            }
            set
            {
                _runningWheel = value;
            }
        }
    
        public System.IObservable<BehaviorBoard> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new BehaviorBoard(this)));
        }
    
        public System.IObservable<BehaviorBoard> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new BehaviorBoard(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("DeviceType = " + _deviceType + ", ");
            stringBuilder.Append("PortName = " + _portName + ", ");
            stringBuilder.Append("PulseController = " + _pulseController + ", ");
            stringBuilder.Append("CameraController = " + _cameraController + ", ");
            stringBuilder.Append("RunningWheel = " + _runningWheel);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Discriminated camera configuration (Arducam or Spinnaker).
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Discriminated camera configuration (Arducam or Spinnaker).")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Camera
    {
    
        public Camera()
        {
        }
    
        protected Camera(Camera other)
        {
        }
    
        public System.IObservable<Camera> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Camera(this)));
        }
    
        public System.IObservable<Camera> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Camera(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            return false;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Represents a CameraController Module for a BehaviourBoard device.
    ///Mirrors the externalized properties of the Bonsai workflow of the same name,
    ///excluding subject name properties.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Represents a CameraController Module for a BehaviourBoard device.\nMirrors the ext" +
        "ernalized properties of the Bonsai workflow of the same name,\nexcluding subject " +
        "name properties.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class CameraController
    {
    
        private int _triggerFrequency;
    
        public CameraController()
        {
        }
    
        protected CameraController(CameraController other)
        {
            _triggerFrequency = other._triggerFrequency;
        }
    
        /// <summary>
        /// The frequency, in Hz, at which to emit camera triggers from DO0 of a behavior board (`CameraOutput0`)
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="triggerFrequency")]
        [System.ComponentModel.DescriptionAttribute("The frequency, in Hz, at which to emit camera triggers from DO0 of a behavior boa" +
            "rd (`CameraOutput0`)")]
        public int TriggerFrequency
        {
            get
            {
                return _triggerFrequency;
            }
            set
            {
                _triggerFrequency = value;
            }
        }
    
        public System.IObservable<CameraController> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new CameraController(this)));
        }
    
        public System.IObservable<CameraController> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new CameraController(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("TriggerFrequency = " + _triggerFrequency);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class DisplayCalibration
    {
    
        private DisplayIntrinsics _intrinsics;
    
        private DisplayExtrinsics _extrinsics;
    
        public DisplayCalibration()
        {
            _intrinsics = new DisplayIntrinsics();
            _extrinsics = new DisplayExtrinsics();
        }
    
        protected DisplayCalibration(DisplayCalibration other)
        {
            _intrinsics = other._intrinsics;
            _extrinsics = other._extrinsics;
        }
    
        /// <summary>
        /// Intrinsics
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="intrinsics")]
        [System.ComponentModel.DescriptionAttribute("Intrinsics")]
        public DisplayIntrinsics Intrinsics
        {
            get
            {
                return _intrinsics;
            }
            set
            {
                _intrinsics = value;
            }
        }
    
        /// <summary>
        /// Extrinsics
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="extrinsics")]
        [System.ComponentModel.DescriptionAttribute("Extrinsics")]
        public DisplayExtrinsics Extrinsics
        {
            get
            {
                return _extrinsics;
            }
            set
            {
                _extrinsics = value;
            }
        }
    
        public System.IObservable<DisplayCalibration> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new DisplayCalibration(this)));
        }
    
        public System.IObservable<DisplayCalibration> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new DisplayCalibration(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Intrinsics = " + _intrinsics + ", ");
            stringBuilder.Append("Extrinsics = " + _extrinsics);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class DisplayExtrinsics
    {
    
        private Vector3 _rotation;
    
        private Vector3 _translation;
    
        public DisplayExtrinsics()
        {
            _rotation = new Vector3();
            _translation = new Vector3();
        }
    
        protected DisplayExtrinsics(DisplayExtrinsics other)
        {
            _rotation = other._rotation;
            _translation = other._translation;
        }
    
        /// <summary>
        /// Rotation vector (radians)
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="rotation")]
        [System.ComponentModel.DescriptionAttribute("Rotation vector (radians)")]
        public Vector3 Rotation
        {
            get
            {
                return _rotation;
            }
            set
            {
                _rotation = value;
            }
        }
    
        /// <summary>
        /// Translation (in cm)
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="translation")]
        [System.ComponentModel.DescriptionAttribute("Translation (in cm)")]
        public Vector3 Translation
        {
            get
            {
                return _translation;
            }
            set
            {
                _translation = value;
            }
        }
    
        public System.IObservable<DisplayExtrinsics> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new DisplayExtrinsics(this)));
        }
    
        public System.IObservable<DisplayExtrinsics> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new DisplayExtrinsics(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Rotation = " + _rotation + ", ");
            stringBuilder.Append("Translation = " + _translation);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class DisplayIntrinsics
    {
    
        private int _frameWidth;
    
        private int _frameHeight;
    
        private double _displayWidth;
    
        private double _displayHeight;
    
        public DisplayIntrinsics()
        {
            _frameWidth = 1920;
            _frameHeight = 1080;
            _displayWidth = 20D;
            _displayHeight = 15D;
        }
    
        protected DisplayIntrinsics(DisplayIntrinsics other)
        {
            _frameWidth = other._frameWidth;
            _frameHeight = other._frameHeight;
            _displayWidth = other._displayWidth;
            _displayHeight = other._displayHeight;
        }
    
        /// <summary>
        /// Frame width (px)
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="frameWidth")]
        [System.ComponentModel.DescriptionAttribute("Frame width (px)")]
        public int FrameWidth
        {
            get
            {
                return _frameWidth;
            }
            set
            {
                _frameWidth = value;
            }
        }
    
        /// <summary>
        /// Frame height (px)
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="frameHeight")]
        [System.ComponentModel.DescriptionAttribute("Frame height (px)")]
        public int FrameHeight
        {
            get
            {
                return _frameHeight;
            }
            set
            {
                _frameHeight = value;
            }
        }
    
        /// <summary>
        /// Display width (cm)
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="displayWidth")]
        [System.ComponentModel.DescriptionAttribute("Display width (cm)")]
        public double DisplayWidth
        {
            get
            {
                return _displayWidth;
            }
            set
            {
                _displayWidth = value;
            }
        }
    
        /// <summary>
        /// Display width (cm)
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="displayHeight")]
        [System.ComponentModel.DescriptionAttribute("Display width (cm)")]
        public double DisplayHeight
        {
            get
            {
                return _displayHeight;
            }
            set
            {
                _displayHeight = value;
            }
        }
    
        public System.IObservable<DisplayIntrinsics> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new DisplayIntrinsics(this)));
        }
    
        public System.IObservable<DisplayIntrinsics> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new DisplayIntrinsics(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("FrameWidth = " + _frameWidth + ", ");
            stringBuilder.Append("FrameHeight = " + _frameHeight + ", ");
            stringBuilder.Append("DisplayWidth = " + _displayWidth + ", ");
            stringBuilder.Append("DisplayHeight = " + _displayHeight);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Experiment
    {
    
        private string _workflow;
    
        private string _commit;
    
        private string _repositoryUrl;
    
        private TestRig _rig;
    
        public Experiment()
        {
            _rig = new TestRig();
        }
    
        protected Experiment(Experiment other)
        {
            _workflow = other._workflow;
            _commit = other._commit;
            _repositoryUrl = other._repositoryUrl;
            _rig = other._rig;
        }
    
        /// <summary>
        /// Path to the workflow running the experiment.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="workflow")]
        [System.ComponentModel.DescriptionAttribute("Path to the workflow running the experiment.")]
        public string Workflow
        {
            get
            {
                return _workflow;
            }
            set
            {
                _workflow = value;
            }
        }
    
        /// <summary>
        /// Commit hash of the experiment/rig repo.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="commit")]
        [System.ComponentModel.DescriptionAttribute("Commit hash of the experiment/rig repo.")]
        public string Commit
        {
            get
            {
                return _commit;
            }
            set
            {
                _commit = value;
            }
        }
    
        /// <summary>
        /// The URL of the git repository used to version experiment source code.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="repositoryUrl")]
        [System.ComponentModel.DescriptionAttribute("The URL of the git repository used to version experiment source code.")]
        public string RepositoryUrl
        {
            get
            {
                return _repositoryUrl;
            }
            set
            {
                _repositoryUrl = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="rig")]
        public TestRig Rig
        {
            get
            {
                return _rig;
            }
            set
            {
                _rig = value;
            }
        }
    
        public System.IObservable<Experiment> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Experiment(this)));
        }
    
        public System.IObservable<Experiment> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Experiment(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Workflow = " + _workflow + ", ");
            stringBuilder.Append("Commit = " + _commit + ", ");
            stringBuilder.Append("RepositoryUrl = " + _repositoryUrl + ", ");
            stringBuilder.Append("Rig = " + _rig);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class LedDriver
    {
    
        private int _digitalOutPin;
    
        public LedDriver()
        {
        }
    
        protected LedDriver(LedDriver other)
        {
            _digitalOutPin = other._digitalOutPin;
        }
    
        /// <summary>
        /// The digital output pin for this LED driver
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="digitalOutPin")]
        [System.ComponentModel.DescriptionAttribute("The digital output pin for this LED driver")]
        public int DigitalOutPin
        {
            get
            {
                return _digitalOutPin;
            }
            set
            {
                _digitalOutPin = value;
            }
        }
    
        public System.IObservable<LedDriver> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new LedDriver(this)));
        }
    
        public System.IObservable<LedDriver> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new LedDriver(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("DigitalOutPin = " + _digitalOutPin);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Represents the PulseController module on the BehaviourBoard.
    ///Mirrors the externalized properties of the Bonsai workflow of the same name,
    ///excluding subject name properties.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Represents the PulseController module on the BehaviourBoard.\nMirrors the external" +
        "ized properties of the Bonsai workflow of the same name,\nexcluding subject name " +
        "properties.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class PulseController
    {
    
        private System.Collections.Generic.List<string> _outputPulseEnable;
    
        private PulseWidths _pulseWidths;
    
        public PulseController()
        {
            _outputPulseEnable = new System.Collections.Generic.List<string>();
            _pulseWidths = new PulseWidths();
        }
    
        protected PulseController(PulseController other)
        {
            _outputPulseEnable = other._outputPulseEnable;
            _pulseWidths = other._pulseWidths;
        }
    
        /// <summary>
        /// List of digital output lines that are enabled for pulse generation.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="outputPulseEnable")]
        [System.ComponentModel.DescriptionAttribute("List of digital output lines that are enabled for pulse generation.")]
        public System.Collections.Generic.List<string> OutputPulseEnable
        {
            get
            {
                return _outputPulseEnable;
            }
            set
            {
                _outputPulseEnable = value;
            }
        }
    
        /// <summary>
        /// Pulse width configuration for DO1, DO2, and DO3 lines.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="pulseWidths")]
        [System.ComponentModel.DescriptionAttribute("Pulse width configuration for DO1, DO2, and DO3 lines.")]
        public PulseWidths PulseWidths
        {
            get
            {
                return _pulseWidths;
            }
            set
            {
                _pulseWidths = value;
            }
        }
    
        public System.IObservable<PulseController> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new PulseController(this)));
        }
    
        public System.IObservable<PulseController> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new PulseController(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("OutputPulseEnable = " + _outputPulseEnable + ", ");
            stringBuilder.Append("PulseWidths = " + _pulseWidths);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class PulseWidths
    {
    
        private int _pulseDO1;
    
        private int _pulseDO2;
    
        private int _pulseDO3;
    
        public PulseWidths()
        {
        }
    
        protected PulseWidths(PulseWidths other)
        {
            _pulseDO1 = other._pulseDO1;
            _pulseDO2 = other._pulseDO2;
            _pulseDO3 = other._pulseDO3;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="PulseDO1")]
        public int PulseDO1
        {
            get
            {
                return _pulseDO1;
            }
            set
            {
                _pulseDO1 = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="PulseDO2")]
        public int PulseDO2
        {
            get
            {
                return _pulseDO2;
            }
            set
            {
                _pulseDO2 = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="PulseDO3")]
        public int PulseDO3
        {
            get
            {
                return _pulseDO3;
            }
            set
            {
                _pulseDO3 = value;
            }
        }
    
        public System.IObservable<PulseWidths> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new PulseWidths(this)));
        }
    
        public System.IObservable<PulseWidths> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new PulseWidths(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("PulseDO1 = " + _pulseDO1 + ", ");
            stringBuilder.Append("PulseDO2 = " + _pulseDO2 + ", ");
            stringBuilder.Append("PulseDO3 = " + _pulseDO3);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Represents the RunningWheel Bonsai workflow module.
    ///Exposes wheel geometry parameters used to compute speed and distance from encoder counts.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Represents the RunningWheel Bonsai workflow module.\nExposes wheel geometry parame" +
        "ters used to compute speed and distance from encoder counts.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class RunningWheelModule
    {
    
        private int _countsPerRev;
    
        private double _wheelDiameterMm;
    
        public RunningWheelModule()
        {
        }
    
        protected RunningWheelModule(RunningWheelModule other)
        {
            _countsPerRev = other._countsPerRev;
            _wheelDiameterMm = other._wheelDiameterMm;
        }
    
        /// <summary>
        /// Number of encoder counts per full revolution of the running wheel.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="countsPerRev")]
        [System.ComponentModel.DescriptionAttribute("Number of encoder counts per full revolution of the running wheel.")]
        public int CountsPerRev
        {
            get
            {
                return _countsPerRev;
            }
            set
            {
                _countsPerRev = value;
            }
        }
    
        /// <summary>
        /// The diameter, in millimeters, of the running wheel.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="wheelDiameterMm")]
        [System.ComponentModel.DescriptionAttribute("The diameter, in millimeters, of the running wheel.")]
        public double WheelDiameterMm
        {
            get
            {
                return _wheelDiameterMm;
            }
            set
            {
                _wheelDiameterMm = value;
            }
        }
    
        public System.IObservable<RunningWheelModule> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new RunningWheelModule(this)));
        }
    
        public System.IObservable<RunningWheelModule> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new RunningWheelModule(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("CountsPerRev = " + _countsPerRev + ", ");
            stringBuilder.Append("WheelDiameterMm = " + _wheelDiameterMm);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Screen
    {
    
        private string _deviceType;
    
        private int _displayIndex;
    
        private double _targetRenderFrequency;
    
        private double _targetUpdateFrequency;
    
        private string _textureAssetsDirectory;
    
        private System.Collections.Generic.Dictionary<string, DisplayCalibration> _calibration;
    
        private double _brightness;
    
        private double _contrast;
    
        public Screen()
        {
            _deviceType = "Screen";
            _displayIndex = 1;
            _targetRenderFrequency = 60D;
            _targetUpdateFrequency = 120D;
            _textureAssetsDirectory = "Textures";
            _brightness = 0D;
            _contrast = 1D;
        }
    
        protected Screen(Screen other)
        {
            _deviceType = other._deviceType;
            _displayIndex = other._displayIndex;
            _targetRenderFrequency = other._targetRenderFrequency;
            _targetUpdateFrequency = other._targetUpdateFrequency;
            _textureAssetsDirectory = other._textureAssetsDirectory;
            _calibration = other._calibration;
            _brightness = other._brightness;
            _contrast = other._contrast;
        }
    
        /// <summary>
        /// Device type
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="deviceType")]
        [System.ComponentModel.DescriptionAttribute("Device type")]
        public string DeviceType
        {
            get
            {
                return _deviceType;
            }
            set
            {
                _deviceType = value;
            }
        }
    
        /// <summary>
        /// Display index
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="displayIndex")]
        [System.ComponentModel.DescriptionAttribute("Display index")]
        public int DisplayIndex
        {
            get
            {
                return _displayIndex;
            }
            set
            {
                _displayIndex = value;
            }
        }
    
        /// <summary>
        /// Target render frequency
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="targetRenderFrequency")]
        [System.ComponentModel.DescriptionAttribute("Target render frequency")]
        public double TargetRenderFrequency
        {
            get
            {
                return _targetRenderFrequency;
            }
            set
            {
                _targetRenderFrequency = value;
            }
        }
    
        /// <summary>
        /// Target update frequency
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="targetUpdateFrequency")]
        [System.ComponentModel.DescriptionAttribute("Target update frequency")]
        public double TargetUpdateFrequency
        {
            get
            {
                return _targetUpdateFrequency;
            }
            set
            {
                _targetUpdateFrequency = value;
            }
        }
    
        /// <summary>
        /// Calibration directory
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="textureAssetsDirectory")]
        [System.ComponentModel.DescriptionAttribute("Calibration directory")]
        public string TextureAssetsDirectory
        {
            get
            {
                return _textureAssetsDirectory;
            }
            set
            {
                _textureAssetsDirectory = value;
            }
        }
    
        /// <summary>
        /// Calibration parameters for a set of named display monitors for visual stimuli
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="calibration")]
        [System.ComponentModel.DescriptionAttribute("Calibration parameters for a set of named display monitors for visual stimuli")]
        public System.Collections.Generic.Dictionary<string, DisplayCalibration> Calibration
        {
            get
            {
                return _calibration;
            }
            set
            {
                _calibration = value;
            }
        }
    
        /// <summary>
        /// Brightness
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="brightness")]
        [System.ComponentModel.DescriptionAttribute("Brightness")]
        public double Brightness
        {
            get
            {
                return _brightness;
            }
            set
            {
                _brightness = value;
            }
        }
    
        /// <summary>
        /// Contrast
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="contrast")]
        [System.ComponentModel.DescriptionAttribute("Contrast")]
        public double Contrast
        {
            get
            {
                return _contrast;
            }
            set
            {
                _contrast = value;
            }
        }
    
        public System.IObservable<Screen> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Screen(this)));
        }
    
        public System.IObservable<Screen> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Screen(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("DeviceType = " + _deviceType + ", ");
            stringBuilder.Append("DisplayIndex = " + _displayIndex + ", ");
            stringBuilder.Append("TargetRenderFrequency = " + _targetRenderFrequency + ", ");
            stringBuilder.Append("TargetUpdateFrequency = " + _targetUpdateFrequency + ", ");
            stringBuilder.Append("TextureAssetsDirectory = " + _textureAssetsDirectory + ", ");
            stringBuilder.Append("Calibration = " + _calibration + ", ");
            stringBuilder.Append("Brightness = " + _brightness + ", ");
            stringBuilder.Append("Contrast = " + _contrast);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Represents the SerialDevice workflow module.
    ///
    ///Mirrors all externalized properties of SerialDevice.bonsai, including
    ///port configuration, framing, buffer settings, and parsing pattern.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Represents the SerialDevice workflow module.\n\nMirrors all externalized properties" +
        " of SerialDevice.bonsai, including\nport configuration, framing, buffer settings," +
        " and parsing pattern.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class SerialDeviceModule
    {
    
        private string _deviceType;
    
        private string _portName;
    
        private int _baudRate;
    
        private string _encoding;
    
        private string _newLine;
    
        private string _parity;
    
        private int _parityReplace;
    
        private int _dataBits;
    
        private string _stopBits;
    
        private string _handshake;
    
        private bool _discardNull;
    
        private bool _dtrEnable;
    
        private bool _rtsEnable;
    
        private int _readBufferSize;
    
        private int _writeBufferSize;
    
        private int _receivedBytesThreshold;
    
        private string _serialMessageSubjectName;
    
        public SerialDeviceModule()
        {
            _deviceType = "SerialDevice";
            _baudRate = 9600;
            _newLine = "\r\n";
            _parity = "None";
            _parityReplace = 63;
            _dataBits = 8;
            _stopBits = "One";
            _handshake = "None";
            _discardNull = false;
            _dtrEnable = false;
            _rtsEnable = false;
            _readBufferSize = 4096;
            _writeBufferSize = 2048;
            _receivedBytesThreshold = 1;
            _serialMessageSubjectName = "SerialMessages";
        }
    
        protected SerialDeviceModule(SerialDeviceModule other)
        {
            _deviceType = other._deviceType;
            _portName = other._portName;
            _baudRate = other._baudRate;
            _encoding = other._encoding;
            _newLine = other._newLine;
            _parity = other._parity;
            _parityReplace = other._parityReplace;
            _dataBits = other._dataBits;
            _stopBits = other._stopBits;
            _handshake = other._handshake;
            _discardNull = other._discardNull;
            _dtrEnable = other._dtrEnable;
            _rtsEnable = other._rtsEnable;
            _readBufferSize = other._readBufferSize;
            _writeBufferSize = other._writeBufferSize;
            _receivedBytesThreshold = other._receivedBytesThreshold;
            _serialMessageSubjectName = other._serialMessageSubjectName;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="deviceType")]
        public string DeviceType
        {
            get
            {
                return _deviceType;
            }
            set
            {
                _deviceType = value;
            }
        }
    
        /// <summary>
        /// The name of the device serial port.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="portName")]
        [System.ComponentModel.DescriptionAttribute("The name of the device serial port.")]
        public string PortName
        {
            get
            {
                return _portName;
            }
            set
            {
                _portName = value;
            }
        }
    
        /// <summary>
        /// Baud rate for serial communication.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="baudRate")]
        [System.ComponentModel.DescriptionAttribute("Baud rate for serial communication.")]
        public int BaudRate
        {
            get
            {
                return _baudRate;
            }
            set
            {
                _baudRate = value;
            }
        }
    
        /// <summary>
        /// Optional text encoding for interpreting incoming bytes.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="encoding")]
        [System.ComponentModel.DescriptionAttribute("Optional text encoding for interpreting incoming bytes.")]
        public string Encoding
        {
            get
            {
                return _encoding;
            }
            set
            {
                _encoding = value;
            }
        }
    
        /// <summary>
        /// Line termination sequence used to delimit incoming messages.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="newLine")]
        [System.ComponentModel.DescriptionAttribute("Line termination sequence used to delimit incoming messages.")]
        public string NewLine
        {
            get
            {
                return _newLine;
            }
            set
            {
                _newLine = value;
            }
        }
    
        /// <summary>
        /// Parity checking mode for the serial port.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="parity")]
        [System.ComponentModel.DescriptionAttribute("Parity checking mode for the serial port.")]
        public string Parity
        {
            get
            {
                return _parity;
            }
            set
            {
                _parity = value;
            }
        }
    
        /// <summary>
        /// Byte used to replace invalid bytes detected by a parity error.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="parityReplace")]
        [System.ComponentModel.DescriptionAttribute("Byte used to replace invalid bytes detected by a parity error.")]
        public int ParityReplace
        {
            get
            {
                return _parityReplace;
            }
            set
            {
                _parityReplace = value;
            }
        }
    
        /// <summary>
        /// Number of data bits per serial frame.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="dataBits")]
        [System.ComponentModel.DescriptionAttribute("Number of data bits per serial frame.")]
        public int DataBits
        {
            get
            {
                return _dataBits;
            }
            set
            {
                _dataBits = value;
            }
        }
    
        /// <summary>
        /// Number of stop bits per serial frame.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="stopBits")]
        [System.ComponentModel.DescriptionAttribute("Number of stop bits per serial frame.")]
        public string StopBits
        {
            get
            {
                return _stopBits;
            }
            set
            {
                _stopBits = value;
            }
        }
    
        /// <summary>
        /// Hardware or software handshaking mode.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="handshake")]
        [System.ComponentModel.DescriptionAttribute("Hardware or software handshaking mode.")]
        public string Handshake
        {
            get
            {
                return _handshake;
            }
            set
            {
                _handshake = value;
            }
        }
    
        /// <summary>
        /// Whether to discard null bytes appearing in the serial stream.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="discardNull")]
        [System.ComponentModel.DescriptionAttribute("Whether to discard null bytes appearing in the serial stream.")]
        public bool DiscardNull
        {
            get
            {
                return _discardNull;
            }
            set
            {
                _discardNull = value;
            }
        }
    
        /// <summary>
        /// Whether to enable Data Terminal Ready (DTR) control line.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="dtrEnable")]
        [System.ComponentModel.DescriptionAttribute("Whether to enable Data Terminal Ready (DTR) control line.")]
        public bool DtrEnable
        {
            get
            {
                return _dtrEnable;
            }
            set
            {
                _dtrEnable = value;
            }
        }
    
        /// <summary>
        /// Whether to enable Request To Send (RTS) control line.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="rtsEnable")]
        [System.ComponentModel.DescriptionAttribute("Whether to enable Request To Send (RTS) control line.")]
        public bool RtsEnable
        {
            get
            {
                return _rtsEnable;
            }
            set
            {
                _rtsEnable = value;
            }
        }
    
        /// <summary>
        /// Size, in bytes, of the read buffer.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="readBufferSize")]
        [System.ComponentModel.DescriptionAttribute("Size, in bytes, of the read buffer.")]
        public int ReadBufferSize
        {
            get
            {
                return _readBufferSize;
            }
            set
            {
                _readBufferSize = value;
            }
        }
    
        /// <summary>
        /// Size, in bytes, of the write buffer.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="writeBufferSize")]
        [System.ComponentModel.DescriptionAttribute("Size, in bytes, of the write buffer.")]
        public int WriteBufferSize
        {
            get
            {
                return _writeBufferSize;
            }
            set
            {
                _writeBufferSize = value;
            }
        }
    
        /// <summary>
        /// Minimum number of bytes in the buffer that triggers a read event.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="receivedBytesThreshold")]
        [System.ComponentModel.DescriptionAttribute("Minimum number of bytes in the buffer that triggers a read event.")]
        public int ReceivedBytesThreshold
        {
            get
            {
                return _receivedBytesThreshold;
            }
            set
            {
                _receivedBytesThreshold = value;
            }
        }
    
        /// <summary>
        /// Name of the subject to which parsed serial messages are published.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="serialMessageSubjectName")]
        [System.ComponentModel.DescriptionAttribute("Name of the subject to which parsed serial messages are published.")]
        public string SerialMessageSubjectName
        {
            get
            {
                return _serialMessageSubjectName;
            }
            set
            {
                _serialMessageSubjectName = value;
            }
        }
    
        public System.IObservable<SerialDeviceModule> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new SerialDeviceModule(this)));
        }
    
        public System.IObservable<SerialDeviceModule> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new SerialDeviceModule(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("DeviceType = " + _deviceType + ", ");
            stringBuilder.Append("PortName = " + _portName + ", ");
            stringBuilder.Append("BaudRate = " + _baudRate + ", ");
            stringBuilder.Append("Encoding = " + _encoding + ", ");
            stringBuilder.Append("NewLine = " + _newLine + ", ");
            stringBuilder.Append("Parity = " + _parity + ", ");
            stringBuilder.Append("ParityReplace = " + _parityReplace + ", ");
            stringBuilder.Append("DataBits = " + _dataBits + ", ");
            stringBuilder.Append("StopBits = " + _stopBits + ", ");
            stringBuilder.Append("Handshake = " + _handshake + ", ");
            stringBuilder.Append("DiscardNull = " + _discardNull + ", ");
            stringBuilder.Append("DtrEnable = " + _dtrEnable + ", ");
            stringBuilder.Append("RtsEnable = " + _rtsEnable + ", ");
            stringBuilder.Append("ReadBufferSize = " + _readBufferSize + ", ");
            stringBuilder.Append("WriteBufferSize = " + _writeBufferSize + ", ");
            stringBuilder.Append("ReceivedBytesThreshold = " + _receivedBytesThreshold + ", ");
            stringBuilder.Append("SerialMessageSubjectName = " + _serialMessageSubjectName);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class SpinnakerCamera
    {
    
        private string _cameraType;
    
        private double _triggerFrequency;
    
        private double _exposureTime;
    
        private string _serialNumber;
    
        private double _gain;
    
        private int _binning;
    
        public SpinnakerCamera()
        {
            _cameraType = "Spinnaker";
            _triggerFrequency = 50D;
            _exposureTime = 15000D;
            _serialNumber = "00000";
            _gain = 1D;
            _binning = 1;
        }
    
        protected SpinnakerCamera(SpinnakerCamera other)
        {
            _cameraType = other._cameraType;
            _triggerFrequency = other._triggerFrequency;
            _exposureTime = other._exposureTime;
            _serialNumber = other._serialNumber;
            _gain = other._gain;
            _binning = other._binning;
        }
    
        /// <summary>
        /// Camera type discriminator for Spinnaker devices.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="cameraType")]
        [System.ComponentModel.DescriptionAttribute("Camera type discriminator for Spinnaker devices.")]
        public string CameraType
        {
            get
            {
                return _cameraType;
            }
            set
            {
                _cameraType = value;
            }
        }
    
        /// <summary>
        /// The frequency at which the camera is triggered (in Hz).
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="triggerFrequency")]
        [System.ComponentModel.DescriptionAttribute("The frequency at which the camera is triggered (in Hz).")]
        public double TriggerFrequency
        {
            get
            {
                return _triggerFrequency;
            }
            set
            {
                _triggerFrequency = value;
            }
        }
    
        /// <summary>
        /// The exposure time for the camera (in microseconds).
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="exposureTime")]
        [System.ComponentModel.DescriptionAttribute("The exposure time for the camera (in microseconds).")]
        public double ExposureTime
        {
            get
            {
                return _exposureTime;
            }
            set
            {
                _exposureTime = value;
            }
        }
    
        /// <summary>
        /// The serial number of the camera.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="serialNumber")]
        [System.ComponentModel.DescriptionAttribute("The serial number of the camera.")]
        public string SerialNumber
        {
            get
            {
                return _serialNumber;
            }
            set
            {
                _serialNumber = value;
            }
        }
    
        /// <summary>
        /// The camera gain.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="gain")]
        [System.ComponentModel.DescriptionAttribute("The camera gain.")]
        public double Gain
        {
            get
            {
                return _gain;
            }
            set
            {
                _gain = value;
            }
        }
    
        /// <summary>
        /// The binning setting for the camera.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="binning")]
        [System.ComponentModel.DescriptionAttribute("The binning setting for the camera.")]
        public int Binning
        {
            get
            {
                return _binning;
            }
            set
            {
                _binning = value;
            }
        }
    
        public System.IObservable<SpinnakerCamera> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new SpinnakerCamera(this)));
        }
    
        public System.IObservable<SpinnakerCamera> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new SpinnakerCamera(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("CameraType = " + _cameraType + ", ");
            stringBuilder.Append("TriggerFrequency = " + _triggerFrequency + ", ");
            stringBuilder.Append("ExposureTime = " + _exposureTime + ", ");
            stringBuilder.Append("SerialNumber = " + _serialNumber + ", ");
            stringBuilder.Append("Gain = " + _gain + ", ");
            stringBuilder.Append("Binning = " + _binning);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class TestRig
    {
    
        private System.Collections.Generic.Dictionary<string, BehaviorBoard> _behaviorBoards;
    
        private System.Collections.Generic.Dictionary<string, Camera2> _cameras;
    
        private System.Collections.Generic.Dictionary<string, ArduinoDevice> _arduinos;
    
        private System.Collections.Generic.Dictionary<string, SerialDeviceModule> _serialDevices;
    
        private Screen _screen;
    
        public TestRig()
        {
            _behaviorBoards = new System.Collections.Generic.Dictionary<string, BehaviorBoard>();
            _cameras = new System.Collections.Generic.Dictionary<string, Camera2>();
            _screen = new Screen();
        }
    
        protected TestRig(TestRig other)
        {
            _behaviorBoards = other._behaviorBoards;
            _cameras = other._cameras;
            _arduinos = other._arduinos;
            _serialDevices = other._serialDevices;
            _screen = other._screen;
        }
    
        /// <summary>
        /// Mapping from logical names to BehaviorBoard devices (e.g. 'main', 'aux').
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="behaviorBoards")]
        [System.ComponentModel.DescriptionAttribute("Mapping from logical names to BehaviorBoard devices (e.g. \'main\', \'aux\').")]
        public System.Collections.Generic.Dictionary<string, BehaviorBoard> BehaviorBoards
        {
            get
            {
                return _behaviorBoards;
            }
            set
            {
                _behaviorBoards = value;
            }
        }
    
        /// <summary>
        /// Mapping from camera role names to camera configurations (e.g. 'body', 'face', 'top').
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="cameras")]
        [System.ComponentModel.DescriptionAttribute("Mapping from camera role names to camera configurations (e.g. \'body\', \'face\', \'to" +
            "p\').")]
        public System.Collections.Generic.Dictionary<string, Camera2> Cameras
        {
            get
            {
                return _cameras;
            }
            set
            {
                _cameras = value;
            }
        }
    
        /// <summary>
        /// Optional mapping from logical names to Arduino devices used in the dome (e.g. for LED drivers or other IO).
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="arduinos")]
        [System.ComponentModel.DescriptionAttribute("Optional mapping from logical names to Arduino devices used in the dome (e.g. for" +
            " LED drivers or other IO).")]
        public System.Collections.Generic.Dictionary<string, ArduinoDevice> Arduinos
        {
            get
            {
                return _arduinos;
            }
            set
            {
                _arduinos = value;
            }
        }
    
        /// <summary>
        /// Optional mapping from logical names to auxiliary serial devices used in the dome.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="serialDevices")]
        [System.ComponentModel.DescriptionAttribute("Optional mapping from logical names to auxiliary serial devices used in the dome." +
            "")]
        public System.Collections.Generic.Dictionary<string, SerialDeviceModule> SerialDevices
        {
            get
            {
                return _serialDevices;
            }
            set
            {
                _serialDevices = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="screen")]
        public Screen Screen
        {
            get
            {
                return _screen;
            }
            set
            {
                _screen = value;
            }
        }
    
        public System.IObservable<TestRig> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new TestRig(this)));
        }
    
        public System.IObservable<TestRig> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new TestRig(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("BehaviorBoards = " + _behaviorBoards + ", ");
            stringBuilder.Append("Cameras = " + _cameras + ", ");
            stringBuilder.Append("Arduinos = " + _arduinos + ", ");
            stringBuilder.Append("SerialDevices = " + _serialDevices + ", ");
            stringBuilder.Append("Screen = " + _screen);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Vector3
    {
    
        private double _x;
    
        private double _y;
    
        private double _z;
    
        public Vector3()
        {
        }
    
        protected Vector3(Vector3 other)
        {
            _x = other._x;
            _y = other._y;
            _z = other._z;
        }
    
        /// <summary>
        /// X coordinate of the point.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="x")]
        [System.ComponentModel.DescriptionAttribute("X coordinate of the point.")]
        public double X
        {
            get
            {
                return _x;
            }
            set
            {
                _x = value;
            }
        }
    
        /// <summary>
        /// Y coordinate of the point.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="y")]
        [System.ComponentModel.DescriptionAttribute("Y coordinate of the point.")]
        public double Y
        {
            get
            {
                return _y;
            }
            set
            {
                _y = value;
            }
        }
    
        /// <summary>
        /// Z coordinate of the point.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="z")]
        [System.ComponentModel.DescriptionAttribute("Z coordinate of the point.")]
        public double Z
        {
            get
            {
                return _z;
            }
            set
            {
                _z = value;
            }
        }
    
        public System.IObservable<Vector3> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Vector3(this)));
        }
    
        public System.IObservable<Vector3> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Vector3(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("X = " + _x + ", ");
            stringBuilder.Append("Y = " + _y + ", ");
            stringBuilder.Append("Z = " + _z);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Discriminated camera configuration (Arducam or Spinnaker).
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Discriminated camera configuration (Arducam or Spinnaker).")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Camera2
    {
    
        public Camera2()
        {
        }
    
        protected Camera2(Camera2 other)
        {
        }
    
        public System.IObservable<Camera2> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Camera2(this)));
        }
    
        public System.IObservable<Camera2> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Camera2(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            return false;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into YAML strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into YAML strings.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [Bonsai.CombinatorAttribute()]
    public partial class SerializeToYaml
    {
    
        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.SerializerBuilder()
                      .WithTypeConverter(new YamlDotNet.Serialization.Converters.DateTimeOffsetConverter())
                      .Build();
                return System.Reactive.Linq.Observable.Select(source, value => serializer.Serialize(value)); 
            });
        }

        public System.IObservable<string> Process(System.IObservable<ArducamOV9180> source)
        {
            return Process<ArducamOV9180>(source);
        }

        public System.IObservable<string> Process(System.IObservable<ArduinoDevice> source)
        {
            return Process<ArduinoDevice>(source);
        }

        public System.IObservable<string> Process(System.IObservable<BehaviorBoard> source)
        {
            return Process<BehaviorBoard>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Camera> source)
        {
            return Process<Camera>(source);
        }

        public System.IObservable<string> Process(System.IObservable<CameraController> source)
        {
            return Process<CameraController>(source);
        }

        public System.IObservable<string> Process(System.IObservable<DisplayCalibration> source)
        {
            return Process<DisplayCalibration>(source);
        }

        public System.IObservable<string> Process(System.IObservable<DisplayExtrinsics> source)
        {
            return Process<DisplayExtrinsics>(source);
        }

        public System.IObservable<string> Process(System.IObservable<DisplayIntrinsics> source)
        {
            return Process<DisplayIntrinsics>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Experiment> source)
        {
            return Process<Experiment>(source);
        }

        public System.IObservable<string> Process(System.IObservable<LedDriver> source)
        {
            return Process<LedDriver>(source);
        }

        public System.IObservable<string> Process(System.IObservable<PulseController> source)
        {
            return Process<PulseController>(source);
        }

        public System.IObservable<string> Process(System.IObservable<PulseWidths> source)
        {
            return Process<PulseWidths>(source);
        }

        public System.IObservable<string> Process(System.IObservable<RunningWheelModule> source)
        {
            return Process<RunningWheelModule>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Screen> source)
        {
            return Process<Screen>(source);
        }

        public System.IObservable<string> Process(System.IObservable<SerialDeviceModule> source)
        {
            return Process<SerialDeviceModule>(source);
        }

        public System.IObservable<string> Process(System.IObservable<SpinnakerCamera> source)
        {
            return Process<SpinnakerCamera>(source);
        }

        public System.IObservable<string> Process(System.IObservable<TestRig> source)
        {
            return Process<TestRig>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Vector3> source)
        {
            return Process<Vector3>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Camera2> source)
        {
            return Process<Camera2>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of YAML strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of YAML strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<ArducamOV9180>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<ArduinoDevice>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<BehaviorBoard>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Camera>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<CameraController>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<DisplayCalibration>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<DisplayExtrinsics>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<DisplayIntrinsics>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Experiment>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<LedDriver>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<PulseController>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<PulseWidths>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<RunningWheelModule>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Screen>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<SerialDeviceModule>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<SpinnakerCamera>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<TestRig>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Vector3>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Camera2>))]
    public partial class DeserializeFromYaml : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromYaml()
        {
            Type = new Bonsai.Expressions.TypeMapping<ArducamOV9180>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromYaml),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.DeserializerBuilder()
                      .WithTypeConverter(new YamlDotNet.Serialization.Converters.DateTimeOffsetConverter())
                      .Build();
                return System.Reactive.Linq.Observable.Select(source, value =>
                {
                    var reader = new System.IO.StringReader(value);
                    var parser = new YamlDotNet.Core.MergingParser(new YamlDotNet.Core.Parser(reader));
                    return serializer.Deserialize<T>(parser);
                });
            });
        }
    }
}